name: Build and Deploy of Static Site

on:
  push:

permissions:
  contents: write
  pages: write

jobs:
  builddeploy:
    name: Build and Install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: MkDocs Setup
        run: pip install mkdocs

      - name: Build
        run: mkdocs build --clean

      - name: Install ESLint
        run: npm install eslint

      - name: Install ESLint dependencies (globals)
        run: npm install globals
        
      - name: Install ESLint dependencies (@eslint/js)
        run: npm install @eslint/js
        
      - name: Install ESLint dependencies (@stylistic/eslint-plugin-js)
        run: npm install @stylistic/eslint-plugin-js

      - name: Install ESLint dependencies (eslint-plugin-html)
        run: npm install eslint-plugin-html

      - name: Using ESLint
        run: npx eslint /home/runner/work/python-web/python-web/site/index.html --fix --debug 

      - name: Deploy
        run: mkdocs gh-deploy --force